#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionDB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UsuariosPrueba")]
	public partial class DBUsuariosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertlistaIP(listaIP instance);
    partial void UpdatelistaIP(listaIP instance);
    partial void DeletelistaIP(listaIP instance);
    partial void Insertusuario(usuario instance);
    partial void Updateusuario(usuario instance);
    partial void Deleteusuario(usuario instance);
    #endregion
		
		public DBUsuariosDataContext() : 
				base(global::ConexionDB.Properties.Settings.Default.UsuariosPruebaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBUsuariosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBUsuariosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBUsuariosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBUsuariosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<listaIP> listaIP
		{
			get
			{
				return this.GetTable<listaIP>();
			}
		}
		
		public System.Data.Linq.Table<usuario> usuario
		{
			get
			{
				return this.GetTable<usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.listaIP")]
	public partial class listaIP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _str_ip;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onstr_ipChanging(string value);
    partial void Onstr_ipChanged();
    #endregion
		
		public listaIP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_str_ip", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string str_ip
		{
			get
			{
				return this._str_ip;
			}
			set
			{
				if ((this._str_ip != value))
				{
					this.Onstr_ipChanging(value);
					this.SendPropertyChanging();
					this._str_ip = value;
					this.SendPropertyChanged("str_ip");
					this.Onstr_ipChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usuario")]
	public partial class usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _int_id;
		
		private string _str_status;
		
		private System.Nullable<System.DateTime> _dat_fecha;
		
		private string _str_nombre;
		
		private string _str_direccion;
		
		private string _str_departamento;
		
		private System.Nullable<int> _int_telefono;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onint_idChanging(int value);
    partial void Onint_idChanged();
    partial void Onstr_statusChanging(string value);
    partial void Onstr_statusChanged();
    partial void Ondat_fechaChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_fechaChanged();
    partial void Onstr_nombreChanging(string value);
    partial void Onstr_nombreChanged();
    partial void Onstr_direccionChanging(string value);
    partial void Onstr_direccionChanged();
    partial void Onstr_departamentoChanging(string value);
    partial void Onstr_departamentoChanged();
    partial void Onint_telefonoChanging(System.Nullable<int> value);
    partial void Onint_telefonoChanged();
    #endregion
		
		public usuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int int_id
		{
			get
			{
				return this._int_id;
			}
			set
			{
				if ((this._int_id != value))
				{
					this.Onint_idChanging(value);
					this.SendPropertyChanging();
					this._int_id = value;
					this.SendPropertyChanged("int_id");
					this.Onint_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_str_status", DbType="VarChar(20)")]
		public string str_status
		{
			get
			{
				return this._str_status;
			}
			set
			{
				if ((this._str_status != value))
				{
					this.Onstr_statusChanging(value);
					this.SendPropertyChanging();
					this._str_status = value;
					this.SendPropertyChanged("str_status");
					this.Onstr_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> dat_fecha
		{
			get
			{
				return this._dat_fecha;
			}
			set
			{
				if ((this._dat_fecha != value))
				{
					this.Ondat_fechaChanging(value);
					this.SendPropertyChanging();
					this._dat_fecha = value;
					this.SendPropertyChanged("dat_fecha");
					this.Ondat_fechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_str_nombre", DbType="VarChar(50)")]
		public string str_nombre
		{
			get
			{
				return this._str_nombre;
			}
			set
			{
				if ((this._str_nombre != value))
				{
					this.Onstr_nombreChanging(value);
					this.SendPropertyChanging();
					this._str_nombre = value;
					this.SendPropertyChanged("str_nombre");
					this.Onstr_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_str_direccion", DbType="VarChar(100)")]
		public string str_direccion
		{
			get
			{
				return this._str_direccion;
			}
			set
			{
				if ((this._str_direccion != value))
				{
					this.Onstr_direccionChanging(value);
					this.SendPropertyChanging();
					this._str_direccion = value;
					this.SendPropertyChanged("str_direccion");
					this.Onstr_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_str_departamento", DbType="VarChar(50)")]
		public string str_departamento
		{
			get
			{
				return this._str_departamento;
			}
			set
			{
				if ((this._str_departamento != value))
				{
					this.Onstr_departamentoChanging(value);
					this.SendPropertyChanging();
					this._str_departamento = value;
					this.SendPropertyChanged("str_departamento");
					this.Onstr_departamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_telefono", DbType="Int")]
		public System.Nullable<int> int_telefono
		{
			get
			{
				return this._int_telefono;
			}
			set
			{
				if ((this._int_telefono != value))
				{
					this.Onint_telefonoChanging(value);
					this.SendPropertyChanging();
					this._int_telefono = value;
					this.SendPropertyChanged("int_telefono");
					this.Onint_telefonoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
